[package]
name = "Shariks"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.21.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.8"
uuid = { version = "1", features = ["v4", "serde"] }

