[package]
name = "shariks_api"
version = "0.1.0"
edition = "2024"

[dependencies]
shariks_core = { path = "../shariks_core" }
dotenv = "0.15"
dotenvy = "0.15.7"
actix-web = "4.10.2"
sqlx = { version = "0.8.5", features = ["runtime-tokio-native-tls", "postgres", "uuid", "time", "chrono"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
actix-cors = "0.6"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.44.2", features = ["full"] }
